url: https://ws-qa01.narvar.qa/api/v1/promise/edd
httpmethod: POST
headers:
  Authorization:
  Content-Type: application/json
post-request-json-file-path: ../promiseRequestBody.json
post-request-json-dynamic-fields:
  items: promise_item
  session_id: uuid
  
#Vegeta
rate: 5 #Vegeta attack rate
duration: 300 #Veteta attack duration

#Dump
dump-request-file-path: ./request_dump.json
dump-attack-results-file-path: ./results.bin
